name: test

channels:
  - openeye
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

  - openff-toolkit-base >=0.9.2
  - pytorch-cpu
  - pydantic

  # --------- openff-system ---------
  - openff-utilities
  - pint
  # --------- openff-system ---------

    # Optional dependencies
  - rdkit
  - ambertools

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - pip:

      - git+git://github.com/openforcefield/openff-units.git
      - git+git://github.com/openforcefield/openff-system.git
