name: smee

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - openff-units
  - openff-toolkit-base >=0.9.2
  - openff-interchange-base >=0.3.17

  - pytorch
  - pydantic
  - nnpops

  # Optional packages

  ### MM simulations
  - openmm
  - python-symengine
  - rdkit
  - packmol
  - numpy
  - msgpack-python

  # Examples
  - jupyter
  - nbconvert
  - nglview
  - smirnoff-plugins >=0.0.4

  # Dev / Testing
  - ambertools
  - scipy  # test logsumexp implementation
  - smirnoff-plugins

  - versioneer

  - pre-commit
  - isort
  - black
  - flake8
  - flake8-pyproject
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov

  # Docs
  - mkdocs <1.6
  - mkdocs-material
  - mkdocs-gen-files
  - mkdocs-literate-nav
  - mkdocs-jupyter
  - mkdocstrings
  - mkdocstrings-python
  - black
  - mike
