name: smee

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - openff-units
  - openff-toolkit-base >=0.9.2
  - openff-interchange-base >=0.3.17

  - pytorch
  - nnpops

  - pydantic
  - pydantic-units

  - networkx

  # Optional packages

  ### MM simulations
  - openmm
  - python-symengine
  - rdkit
  - packmol
  - numpy
  - msgpack-python

  # FE simulations
  - mdtraj
  - absolv >=1.0.1

  # Examples
  - jupyter
  - nbconvert
  - nglview
  - smirnoff-plugins >=0.0.4

  # Dev / Testing
  - ambertools
  - scipy  # test logsumexp implementation
  - smirnoff-plugins

  - setuptools_scm >=8

  - pre-commit
  - ruff
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov

  # Docs
  - mkdocs
  - mkdocs-material
  - mkdocs-gen-files
  - mkdocs-literate-nav
  - mkdocs-jupyter
  - mkdocstrings
  - mkdocstrings-python >=1.10.8
  - griffe-pydantic
  - black
  - mike
