name: smee

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - openff-units
  - openff-toolkit-base >=0.9.2
  - openff-interchange-base >=0.3.15

  - pytorch-cpu
  - pydantic

  # Optional packages

  ### MM simulations
  - openmm
  - rdkit
  - packmol

  # Examples
  - jupyter
  - nbconvert
  - nglview
  - smirnoff-plugins >=0.0.4

  # Dev / Testing
  - ambertools

  - versioneer

  - pre-commit
  - isort
  - black
  - flake8
  - flake8-pyproject
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov
